services:
  postgres:
    image: postgres:latest
    container_name: mytradescontainer
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: krishna.manne9
      POSTGRES_PASSWORD: mytrades@123
      POSTGRES_DB: mytrades
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=krishna.manne9@live.com
      - PGADMIN_DEFAULT_PASSWORD=mytrades@123
    ports:
      - "8001:80"
    depends_on:
      - postgres
  
  aspiredashboard:
    image: mcr.microsoft.com/dotnet/aspire-dashboard
    container_name: aspiredashboard
    ports:
      - "18888:18888"
      - "18889:18889"
      - "18890:18890"

volumes:
  postgres-data: 

